// Monomind native Codex hook bridge (generated by monomind init --codex).
const { spawnSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

let input = "";
process.stdin.on("data", (chunk) => { input += chunk; });
process.stdin.on("end", () => {
  let payload = {};
  try { payload = JSON.parse(input || "{}"); } catch (_) { process.exit(0); }
  const cwd = payload.cwd || process.cwd();
  const handler = path.join(cwd, ".claude", "helpers", "hook-handler.cjs");
  if (!fs.existsSync(handler)) process.exit(0);

  const eventName = payload.hook_event_name || "";
  const tool = payload.tool_name || "";
  const toolInput = payload.tool_input || {};
  const shellTools = new Set(["shell_command", "exec_command", "command_execution", "Bash"]);
  const writeTools = new Set(["apply_patch", "edit", "write", "file_edit", "Write", "Edit", "MultiEdit"]);
  let event = null;
  let gateInput = {};
  if (eventName === "PreToolUse" && shellTools.has(tool)) {
    event = "pre-bash";
    gateInput = { command: toolInput.command || toolInput.cmd || toolInput.shell_command || "" };
  } else if (eventName === "PreToolUse" && writeTools.has(tool)) {
    event = "pre-write";
    gateInput = toolInput;
  } else if (eventName === "PostToolUse" && writeTools.has(tool)) {
    event = "post-edit";
    gateInput = toolInput;
  } else if (eventName === "SessionStart") {
    event = "session-restore";
  } else if (eventName === "SessionEnd") {
    event = "session-end";
  }
  if (!event) process.exit(0);

  let result;
  try {
    result = spawnSync(process.execPath, [handler, event], {
      input: JSON.stringify({ tool_name: tool, tool_input: gateInput, session_id: payload.session_id || "" }),
      encoding: "utf8",
      timeout: eventName === "SessionStart" || eventName === "SessionEnd" ? 2500 : 5000,
      cwd,
      env: Object.assign({}, process.env, { CLAUDE_PROJECT_DIR: cwd }),
    });
  } catch (_) { process.exit(0); }
  if (!result || result.status !== 2) process.exit(0);

  let reason = "blocked by Monomind gate";
  for (const line of (result.stderr || "").split("\n")) {
    try {
      const parsed = JSON.parse(line);
      if (parsed && parsed.decision === "block" && parsed.reason) { reason = parsed.reason; break; }
    } catch (_) {}
  }
  console.error("[monomind] " + reason);
  process.exit(2);
});
