// monomind gate bridge for Kimi Code hooks (generated by monomind init --kimicode).
// Reads kimi's hook payload on stdin, forwards to .claude/helpers/hook-handler.cjs,
// maps exit code 2 back to a block. Fails OPEN when the handler is absent or errors,
// matching both platforms' "hook errors never block" policy.
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

let input = "";
process.stdin.on("data", (c) => { input += c; });
process.stdin.on("end", () => {
  let payload = {};
  try { payload = JSON.parse(input || "{}"); } catch (e) { process.exit(0); }
  const cwd = payload.cwd || process.cwd();
  const handler = path.join(cwd, ".claude", "helpers", "hook-handler.cjs");
  if (!fs.existsSync(handler)) process.exit(0); // gates not installed -> nothing to enforce

  const tool = payload.tool_name || "";
  let event = null;
  let gateInput = {};
  if (tool === "Bash") {
    event = "pre-bash";
    gateInput = { command: payload.tool_input && payload.tool_input.command };
  } else if (tool === "Write" || tool === "Edit" || tool === "MultiEdit") {
    event = "pre-write";
    gateInput = payload.tool_input || {};
  } else if (tool === "Grep" || tool === "Glob") {
    // Graph-first gate: search tools must consult monograph before grep/glob
    // (once-per-session block, then warn) — same rule as Claude's pre-search.
    event = "pre-search";
    gateInput = payload.tool_input || {};
  }
  if (!event) process.exit(0);

  let r;
  try {
    r = spawnSync(process.execPath, [handler, event], {
      input: JSON.stringify({ tool_name: tool, tool_input: gateInput, session_id: payload.session_id || "" }),
      encoding: "utf-8",
      timeout: 5000,
      cwd: cwd,
      env: Object.assign({}, process.env, { CLAUDE_PROJECT_DIR: cwd }),
    });
  } catch (e) {
    process.exit(0);
  }
  if (!r || r.status !== 2) process.exit(0);

  let reason = "blocked by monomind gate";
  const lines = (r.stderr || "").split("\n");
  for (let i = 0; i < lines.length; i++) {
    try {
      const obj = JSON.parse(lines[i]);
      if (obj && obj.decision === "block" && obj.reason) { reason = obj.reason; break; }
    } catch (e) {}
  }
  console.error("[monomind] " + reason);
  process.exit(2);
});
